### ISSUE TITLE
Error when listing configurations of empty workspace

### ISSUE THREAD

**Issue by hans-permana** [DeDop/dedop-core#11]
## Scenario
`dedop w add newWorkSpace`
`dedop c ls`

## Issue

```
> dedop c ls
Traceback (most recent call last):
  File "C:\Users\hans\DeDop\Scripts\dedop-script.py", line 5, in <module>
    sys.exit(dedop.ui.cli.main())
  File "C:\Users\hans\DeDop\lib\site-packages\dedop\ui\cli.py", line 1268, in main
    status_and_message = args_obj.command_class().execute(args_obj)
  File "C:\Users\hans\DeDop\lib\site-packages\dedop\ui\cli.py", line 512, in execute
    return command_args.cf_command(command_args)
  File "C:\Users\hans\DeDop\lib\site-packages\dedop\ui\cli.py", line 646, in execute_list
    num_configs = len(config_names)
TypeError: object of type 'NoneType' has no len() 
```

**Comment by mark-ep** [comment]
this issue has been fixed in commit https://github.com/DeDop/dedop-core/commit/1d0fc43c38890c5d9f463baefafb203a0e961163
